word_list = [
    "apple", "banana", "cat", "dog", "elephant", "fish", "grape", "hat", "ice cream", "jacket",
    "kite", "lion", "monkey", "noodle", "orange", "penguin", "queen", "rabbit", "snake", "tiger",
    "umbrella", "violin", "watermelon", "xylophone", "yogurt", "zebra", "airplane", "basketball", "car", "duck",
    "eagle", "frog", "guitar", "hamburger", "ice", "jellyfish", "kangaroo", "lemon", "mango", "ninja",
    "octopus", "parrot", "quokka", "raccoon", "strawberry", "toucan", "unicorn", "volcano", "whale", "xylophone",
    "yacht", "zeppelin", "ant", "bear", "camel", "dolphin", "elephant", "flamingo", "giraffe", "hedgehog",
    "iguana", "jaguar", "koala", "lemur", "meerkat", "narwhal", "octopus", "panda", "quokka", "rhinoceros",
    "sloth", "toucan", "urutu", "vampire", "walrus", "x-ray fish", "yak", "zebra", "apple", "banana",
    "carrot", "date", "eggplant", "fig", "grape", "honeydew", "kiwi", "lemon", "mango", "nectarine",
    "orange", "peach", "quince", "raspberry", "strawberry", "tomato", "watermelon", "avocado", "broccoli", "cabbage",
    "cucumber", "egg", "lettuce", "onion", "pepper", "spinach", "zucchini", "blueberry", "cherry", "coconut",
    "dragonfruit", "elderberry", "fennel", "grapefruit", "honey", "jackfruit", "kiwifruit", "lime", "mulberry", "nutmeg",
    "olive", "papaya", "quinoa", "radish", "starfruit", "tangerine", "uva", "vanilla", "watercress", "xigua",
    "yam", "zucchini", "almond", "blackberry", "cantaloupe", "date", "elderberry", "fig", "grape", "honeydew",
    "ice cream", "jicama", "kale", "leek", "mango", "nectarine", "olive", "pepper", "quince", "rhubarb",
    "spinach", "tangerine", "umeboshi", "vanilla", "watermelon", "xigua", "yogurt", "zucchini", "avocado", "blueberry",
    "cantaloupe", "date", "elderberry", "fig", "grape", "honeydew", "ice cream", "jicama", "kale", "leek",
    "mango", "nectarine", "olive", "pepper", "quince", "rhubarb", "spinach", "tangerine", "umeboshi", "vanilla",
    "watermelon", "xigua", "yogurt", "zucchini", "avocado", "blueberry", "cantaloupe", "date", "elderberry", "fig",
    "grape", "honeydew", "ice cream", "jicama", "kale", "leek", "mango", "nectarine", "olive", "pepper", "quince",
    "rhubarb", "spinach", "tangerine", "umeboshi", "vanilla", "watermelon", "xigua", "yogurt", "zucchini",
]


